language: elixir
elixir: '1.4'
sudo: required
dist: xenial
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq software-properties-common
  - sudo add-apt-repository -y ppa:mc3man/xerus-media
  - sudo apt-get update -qq
  - sudo apt-get install -qq ffmpeg
