name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-18.04
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['20.0']
        elixir: ['1.9.4']
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install ffmpeg
        run: |
          sudo apt-get install -qq software-properties-common
          sudo add-apt-repository -y ppa:mc3man/bionic-media
          sudo apt-get update -qq
          sudo apt-get install -qq ffmpeg
      - run: mix deps.get
      - run: mix test